/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numrical;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Third_Question extends javax.swing.JFrame {

    /**
     * Creates new form Third_Question
     */
    public Third_Question() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        z = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        c = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Third Question");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Xi (X initial)");

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Yi(Y initial)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("X ");
        jLabel4.setToolTipText("");

        z.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        z.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        z.setEnabled(false);
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("number of iterations");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("y");

        w.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        w.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        w.setEnabled(false);
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Third Question:");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Previous Question");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton2)
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(89, 89, 89)
                                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(89, 89, 89)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(z, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    public double vi(double xi,double yi) {
		double y;
		y=(0.45*Math.cos(xi))-(0.28*Math.cos(yi))-0.275;
		return y;
	}
    public double ui(double xi,double yi) {
		double y;
		y=(0.45*Math.sin(xi))-(0.28*Math.sin(yi))-0.13;
		return y;
	}
      public double vi_xi(double xi) {
		double y;
		y=0.45*Math.cos(xi);
		return y;
	}
       public double ui_xi(double xi) {
		double y;
		y=-0.45*Math.sin(xi);
		return y;
	}
       public double vi_yi(double yi) {
		double y;
		y=-0.28*Math.cos(yi);
		return y;
	}
         public double ui_yi(double yi) {
		double y;
		y=0.28*Math.sin(yi);
		return y;
	}
       public double calc_xi_new(double xi,double vi,double ui,double vi_xi,double ui_xi,double vi_yi,double ui_yi){
           double y;
           y=xi-((ui*vi_yi-vi*ui_yi)/(ui_xi*vi_yi-vi_xi*ui_yi));
           return y;  
       }
        public double calc_yi_new(double yi,double vi,double ui,double vi_xi,double ui_xi,double vi_yi,double ui_yi){
           double y;
           y=yi-((vi*ui_xi-ui*vi_xi)/(ui_xi*vi_yi-vi_xi*ui_yi));
           return y;  
       }
        public double calcERRORx(double x_old,double xi){
         double y;
         y=Math.abs((xi-x_old)/xi)*100;
         return y;
     }
         public double calcERRORy(double y_old,double yi){
         double y;
         y=Math.abs((yi-y_old)/yi)*100;
         return y;
     }
       
       
    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(a.getText().equals("")){
   JOptionPane.showMessageDialog(Third_Question.this,"Xi is empty");
   return;}
if(b.getText().equals("")){
    JOptionPane.showMessageDialog(Third_Question.this,"Yi is empty");
    return;}
if(c.getText().equals("")){
    JOptionPane.showMessageDialog(Third_Question.this,"Number of iterations is empty");
    return;}  

    String aa=a.getText();
    String bb=b.getText();
    String cc=c.getText();
    
    for(int i=0;i<aa.length();i++) {
      if(!(aa.charAt(i)>='0'&&aa.charAt(i)<='9')&&(aa.charAt(i)!='.')){
      JOptionPane.showMessageDialog(Third_Question.this, "Xi Should be a number ", "WARNING", JOptionPane.WARNING_MESSAGE);
      return;
      }
    }
     for(int i=0;i<bb.length();i++) {
      if(!(bb.charAt(i)>='0'&&bb.charAt(i)<='9')&&(bb.charAt(i)!='.')){
      JOptionPane.showMessageDialog(Third_Question.this, "Yi Should be a number ", "WARNING", JOptionPane.WARNING_MESSAGE);
      return;
      }
    }
      for(int i=0;i<cc.length();i++) {
      if(!(cc.charAt(i)>='0'&&cc.charAt(i)<='9')&&(cc.charAt(i)!='.')){
      JOptionPane.showMessageDialog(Third_Question.this, "Number of iterations Should be a number ", "WARNING", JOptionPane.WARNING_MESSAGE);
      return;
      }
    }

double xi;
double yi;
double xi_old;
double yi_old;
double vi;
double ui;
double vi_xi;
double ui_xi;
double vi_yi;
double ui_yi;
double errorx1;
double errorx2;
double errorx3;
double errory1;
double errory2;
double errory3;
double counter=Double.parseDouble(c.getText());

xi=Double.parseDouble(a.getText());
yi=Double.parseDouble(b.getText());
    vi=vi(xi,yi);
    ui=ui(xi,yi);
    vi_xi=vi_xi(xi);
    ui_xi=ui_xi(xi);
    vi_yi=vi_yi(yi);
    ui_yi=ui_yi(yi);
    xi_old=xi;
    yi_old=yi;
    xi=calc_xi_new(xi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    yi=calc_yi_new(yi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    errorx1=calcERRORx(xi_old,xi);
    errory1=calcERRORy(yi_old,yi);
    vi=vi(xi,yi);
    ui=ui(xi,yi);
    vi_xi=vi_xi(xi);
    ui_xi=ui_xi(xi);
    vi_yi=vi_yi(yi);
    ui_yi=ui_yi(yi);
    xi_old=xi;
    yi_old=yi;
    xi=calc_xi_new(xi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    yi=calc_yi_new(yi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    errorx2=calcERRORx(xi_old,xi);
    errory2=calcERRORy(yi_old,yi);
    vi=vi(xi,yi);
    ui=ui(xi,yi);
    vi_xi=vi_xi(xi);
    ui_xi=ui_xi(xi);
    vi_yi=vi_yi(yi);
    ui_yi=ui_yi(yi);
    xi_old=xi;
    yi_old=yi;
    xi=calc_xi_new(xi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    yi=calc_yi_new(yi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    errorx3=calcERRORx(xi_old,xi);
    errory3=calcERRORy(yi_old,yi);


 
 
 
 
 
if(((errorx3>errorx2)&&(errorx2>errorx1))||((errory3>errory2)&&(errory2>errory1))){
    JOptionPane.showMessageDialog(Third_Question.this, "initial guesses is wrong", "WARNING", JOptionPane.WARNING_MESSAGE);
    return;
}
else{
    xi=Double.parseDouble(a.getText());
    yi=Double.parseDouble(b.getText());
while(true){
    if(counter==0)
        break;
    
    vi=vi(xi,yi);
    ui=ui(xi,yi);
    vi_xi=vi_xi(xi);
    ui_xi=ui_xi(xi);
    vi_yi=vi_yi(yi);
    ui_yi=ui_yi(yi);
    xi=calc_xi_new(xi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    yi=calc_yi_new(yi,vi,ui,vi_xi,ui_xi,vi_yi,ui_yi);
    counter--;
}
 z.setText(xi+"");
 w.setText(yi+"");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

Second_Question v=new Second_Question();
this.dispose();
v.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Third_Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Third_Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField w;
    private javax.swing.JTextField z;
    // End of variables declaration//GEN-END:variables
}
